# Cloud Build configuration for SkyCap AI
# Builds the container and deploys to Cloud Run with required env vars.

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

substitutions:
  _SERVICE_NAME: skycap-ai-service
  _REGION: europe-west1
  _VERTEX_MODEL_NAME: gemini-2.5-flash
  _VERTEX_LOCATION: europe-west1
  _SEMANTIC_INDEX_GCS_URI: ""
  _AR_LOCATION: europe-west1
  _AR_REPO: skycap-ai

steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build image'
    args:
      - build
      - -t
      - '$_AR_LOCATION-docker.pkg.dev/$PROJECT_ID/$_AR_REPO/skycap-ai:latest'
      - .
      - --build-arg
      - 'GCP_PROJECT=$PROJECT_ID'
      - --build-arg
      - 'GCP_REGION=$_REGION'
      - --build-arg
      - 'VERTEX_MODEL_NAME=$_VERTEX_MODEL_NAME'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push image'
    args:
      - push
      - '$_AR_LOCATION-docker.pkg.dev/$PROJECT_ID/$_AR_REPO/skycap-ai:latest'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy to Cloud Run'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - '$_SERVICE_NAME'
      - --project
      - '$PROJECT_ID'
      - --region
      - '$_REGION'
      - --image
      - '$_AR_LOCATION-docker.pkg.dev/$PROJECT_ID/$_AR_REPO/skycap-ai:latest'
      - --platform
      - managed
      - --allow-unauthenticated
      - --service-account
      - 'skycap-ai-server@skycap-ai-final-project.iam.gserviceaccount.com'
      - --set-env-vars
      - 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID,GOOGLE_CLOUD_REGION=$_REGION,GOOGLE_CLOUD_LOCATION=$_VERTEX_LOCATION,VERTEX_MODEL_NAME=$_VERTEX_MODEL_NAME,SEMANTIC_INDEX_GCS_URI=$_SEMANTIC_INDEX_GCS_URI'

images:
  - '$_AR_LOCATION-docker.pkg.dev/$PROJECT_ID/$_AR_REPO/skycap-ai:latest'
